[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "prague"
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
bsc-testnet = "${BSC_TESTNET_URL}"
bsc = "${BSC_URL}"

[etherscan]
bsc-testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://testnet.bscscan.com/api" }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
